# Generated by Django 3.1.7 on 2021-06-22 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام و نام خانوادگی')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='تلفن همراه')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس')),
                ('pelak', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('p1', models.IntegerField(blank=True, null=True, verbose_name='دو رقم اول پلاک')),
                ('p2', models.CharField(blank=True, max_length=5, null=True, verbose_name='حرف پلاک')),
                ('p3', models.IntegerField(blank=True, null=True, verbose_name='سه رقم پلاک')),
                ('p4', models.IntegerField(blank=True, null=True, verbose_name='ایران')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
            ],
            options={
                'verbose_name': 'بیمه گذار',
                'verbose_name_plural': 'بیمه گذاران',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1399', '1399'), ('1400', '1400'), ('1401', '1401'), ('1402', '1402'), ('1403', '1403'), ('1404', '1404'), ('1405', '1405'), ('1406', '1406'), ('1407', '1407'), ('1408', '1408'), ('1409', '1409')], default='1400', max_length=4, verbose_name='سال')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False, verbose_name='اتمام')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurer', to='bazdidkhodro.insurer', verbose_name='بیمه گذار')),
                ('visitor', models.ForeignKey(limit_choices_to={'groups__name': 'visitor'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='تصویر')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bazdidkhodro.visit')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ('-id',),
            },
        ),
    ]
