# Generated by Django 3.1.7 on 2021-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazdidkhodro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='p1',
            field=models.IntegerField(blank=True, verbose_name='دو رقم اول پلاک'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='p2',
            field=models.CharField(blank=True, max_length=5, verbose_name='حرف پلاک'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='p3',
            field=models.IntegerField(blank=True, verbose_name='سه رقم پلاک'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='p4',
            field=models.IntegerField(blank=True, verbose_name='ایران'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='pelak',
            field=models.CharField(blank=True, max_length=20, verbose_name='پلاک'),
        ),
    ]
