# Generated by Django 3.1.7 on 2021-07-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazdidkhodro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='insurer',
        ),
    ]
