# Generated by Django 3.1.7 on 2021-07-10 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazdidkhodro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'visitor'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visitor', to=settings.AUTH_USER_MODEL, verbose_name='بازدید کننده'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d', verbose_name='فایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazdidkhodro.insurer')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
                'ordering': ('-id',),
            },
        ),
    ]
