# Generated by Django 3.1.7 on 2021-07-31 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazdidkhodro', '0003_menuitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'ordering': ('-id',), 'verbose_name': 'منو اپلیکیشن', 'verbose_name_plural': 'منو های اپلیکیشن'},
        ),
        migrations.CreateModel(
            name='MobileSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=25, verbose_name='نوع')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='bazdidkhodro.menuitems', verbose_name='لینک وارد شده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
