# Generated by Django 3.1.7 on 2021-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazdidkhodro', '0003_auto_20210614_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='تلفن همراه'),
        ),
    ]
