# Generated by Django 3.1.7 on 2021-07-31 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazdidkhodro', '0004_auto_20210731_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilesignal',
            old_name='action_date',
            new_name='enter_date',
        ),
        migrations.AddField(
            model_name='mobilesignal',
            name='leave_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
