# Generated by Django 3.1.7 on 2021-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazdidkhodro', '0005_auto_20210731_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilesignal',
            name='leave_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
