# Generated by Django 3.1.7 on 2021-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazdidkhodro', '0006_auto_20210731_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilesignal',
            name='leave_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
