# Generated by Django 3.1.7 on 2021-08-11 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نوع بایگانی',
                'verbose_name_plural': 'انواع بایگانی',
            },
        ),
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_archive/%Y/%m/%d', verbose_name='فایل')),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documentarchive.doctype', verbose_name='نوع بایگانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_archives', to=settings.AUTH_USER_MODEL, verbose_name='نام بیمه گذار')),
            ],
            options={
                'verbose_name': 'بایگانی',
                'verbose_name_plural': 'بایگانی ها',
            },
        ),
    ]
