# Generated by Django 3.1.7 on 2021-08-14 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100, verbose_name='نام شبکه وایرلس روتر')),
                ('bssid', models.CharField(max_length=100, verbose_name='مک آدرس روتر')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تنظیمات روتر',
                'verbose_name_plural': 'تنظیمات روترها',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(blank=True, default=None, null=True, verbose_name='تاریخ')),
                ('enter_time', models.TimeField(default=None, verbose_name='ساعت ورود')),
                ('exit_time', models.TimeField(blank=True, default=None, null=True, verbose_name='ساعت خروج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL, verbose_name='نام کارمند')),
            ],
            options={
                'verbose_name': 'ورود- خروج کارمند',
                'verbose_name_plural': 'ورود-خروج کارمندان',
            },
        ),
        migrations.CreateModel(
            name='TimeSheetProxy',
            fields=[
            ],
            options={
                'verbose_name': 'گزارش ورود خروج کارمند',
                'verbose_name_plural': 'گزارش ورود خروج کارمندان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('timesheet.timesheet',),
        ),
    ]
