# Generated by Django 3.1.7 on 2021-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktime', models.IntegerField(default=176, unique=True, verbose_name='حداکثر ساعت کاری')),
                ('extraworktime', models.IntegerField(default=120, unique=True, verbose_name='حداکثر ساعت اضافه کاری')),
                ('workamount', models.CharField(default=80000, max_length=50, unique=True, verbose_name='دستمزد یک ساعت کاری')),
                ('extraworkamount', models.CharField(default=170000, max_length=50, unique=True, verbose_name='دستمزد یک ساعت اضافه کاری')),
            ],
            options={
                'verbose_name': 'تنظمیات حقوق',
                'verbose_name_plural': 'تنظیمات حقوق',
            },
        ),
        migrations.DeleteModel(
            name='TempTimeSheetProxy',
        ),
        migrations.CreateModel(
            name='CalcSalaryTimeSheetProxy',
            fields=[
            ],
            options={
                'verbose_name': 'محاسبه حقوق و دستمزد',
                'verbose_name_plural': 'محاسبه حقوق و دستمزد',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('timesheet.timesheet',),
        ),
    ]
