# Generated by Django 3.1.7 on 2021-09-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_commission_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='slug',
        ),
    ]
