# Generated by Django 3.1.7 on 2021-09-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_remove_commission_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پورسانت')),
                ('amount', models.CharField(default=0, max_length=50, verbose_name='مبلغ')),
            ],
            options={
                'verbose_name': 'پورسانت مبلغی',
                'verbose_name_plural': 'پورسانت ها مبلغی',
            },
        ),
        migrations.CreateModel(
            name='CommissionPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پورسانت')),
                ('percentage', models.CharField(default=0, max_length=50, verbose_name='درصد')),
            ],
            options={
                'verbose_name': 'پورسانت درصدی',
                'verbose_name_plural': 'پورسانت ها درصدی',
            },
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='TimeSheetProxy',
        ),
    ]
